stages:
  - test
  - build

before_script:
  - export GOPATH=~/go
  - export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  - make dep

lint_code:
  stage: test
  script:
    - make lint

unit_tests:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make
