stages:
  - test
  - build

before_script:
  - export GOPATH=~/go
  - export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  - export CC=clang-5.0
  - make dep

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make
